"""Add node_type to IvrNode

Revision ID: 445815aa1e18
Revises: 9d7560b63b4b
Create Date: 2026-04-08 23:04:49.686951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '445815aa1e18'
down_revision: Union[str, Sequence[str], None] = '9d7560b63b4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == 'postgresql':
        op.execute("CREATE TYPE ivrnodetype AS ENUM ('PROMPT', 'HANGUP', 'TRANSFER', 'DNC')")
        
    op.add_column('ivr_nodes', sa.Column('node_type', sa.Enum('PROMPT', 'HANGUP', 'TRANSFER', 'DNC', name='ivrnodetype'), server_default='PROMPT', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ivr_nodes', 'node_type')
    if op.get_bind().dialect.name == 'postgresql':
        op.execute("DROP TYPE ivrnodetype")
    # ### end Alembic commands ###
