"""Add CallLog model

Revision ID: 76f068e4e8a8
Revises: 95671f786cce
Create Date: 2026-04-07 19:14:30.938152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76f068e4e8a8'
down_revision: Union[str, Sequence[str], None] = '95671f786cce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('phone_number', sa.String(length=30), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('hangup_cause', sa.String(length=255), nullable=True),
    sa.Column('amd_result', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_logs_campaign_id'), 'call_logs', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_call_logs_contact_id'), 'call_logs', ['contact_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_call_logs_contact_id'), table_name='call_logs')
    op.drop_index(op.f('ix_call_logs_campaign_id'), table_name='call_logs')
    op.drop_table('call_logs')
    # ### end Alembic commands ###
