"""ivr_tree_schema

Revision ID: 95671f786cce
Revises: c46b9fd6ddc7
Create Date: 2026-04-07 05:15:14.047807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '95671f786cce'
down_revision: Union[str, Sequence[str], None] = 'c46b9fd6ddc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ivr_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('script_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('is_start_node', sa.Boolean(), nullable=True),
    sa.Column('prompt_audio_id', sa.UUID(), nullable=True),
    sa.Column('tts_text', sa.Text(), nullable=True),
    sa.Column('tts_voice', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['prompt_audio_id'], ['audio_files.id'], ),
    sa.ForeignKeyConstraint(['script_id'], ['call_scripts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ivr_nodes_script_id'), 'ivr_nodes', ['script_id'], unique=False)
    op.create_table('ivr_routes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('key_pressed', sa.String(length=10), nullable=False),
    sa.Column('action_type', sa.Enum('TRANSFER', 'HANGUP', 'GO_TO_NODE', 'DNC', name='ivractiontype'), nullable=False),
    sa.Column('target_node_id', sa.UUID(), nullable=True),
    sa.Column('response_audio_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['ivr_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['response_audio_id'], ['audio_files.id'], ),
    sa.ForeignKeyConstraint(['target_node_id'], ['ivr_nodes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ivr_routes_node_id'), 'ivr_routes', ['node_id'], unique=False)
    op.drop_table('script_steps')
    op.drop_constraint(op.f('call_scripts_wrong_key_response_audio_id_fkey'), 'call_scripts', type_='foreignkey')
    op.drop_constraint(op.f('call_scripts_hangup_response_audio_id_fkey'), 'call_scripts', type_='foreignkey')
    op.drop_constraint(op.f('call_scripts_transfer_response_audio_id_fkey'), 'call_scripts', type_='foreignkey')
    op.drop_column('call_scripts', 'hangup_response_audio_id')
    op.drop_column('call_scripts', 'transfer_key')
    op.drop_column('call_scripts', 'transfer_response_audio_id')
    op.drop_column('call_scripts', 'hangup_key')
    op.drop_column('call_scripts', 'enable_wrong_key_response')
    op.drop_column('call_scripts', 'wrong_key_response_audio_id')
    op.drop_column('call_scripts', 'enable_hangup_response')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call_scripts', sa.Column('enable_hangup_response', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('call_scripts', sa.Column('wrong_key_response_audio_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('call_scripts', sa.Column('enable_wrong_key_response', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('call_scripts', sa.Column('hangup_key', sa.VARCHAR(length=1), autoincrement=False, nullable=True))
    op.add_column('call_scripts', sa.Column('transfer_response_audio_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('call_scripts', sa.Column('transfer_key', sa.VARCHAR(length=1), autoincrement=False, nullable=True))
    op.add_column('call_scripts', sa.Column('hangup_response_audio_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('call_scripts_transfer_response_audio_id_fkey'), 'call_scripts', 'audio_files', ['transfer_response_audio_id'], ['id'])
    op.create_foreign_key(op.f('call_scripts_hangup_response_audio_id_fkey'), 'call_scripts', 'audio_files', ['hangup_response_audio_id'], ['id'])
    op.create_foreign_key(op.f('call_scripts_wrong_key_response_audio_id_fkey'), 'call_scripts', 'audio_files', ['wrong_key_response_audio_id'], ['id'])
    op.create_table('script_steps',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('script_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('step_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('step_type', postgresql.ENUM('AUDIO_FILE', 'TTS', name='scriptsteptype'), autoincrement=False, nullable=False),
    sa.Column('audio_file_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('tts_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tts_voice', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('playlist_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['audio_file_id'], ['audio_files.id'], name=op.f('script_steps_audio_file_id_fkey')),
    sa.ForeignKeyConstraint(['script_id'], ['call_scripts.id'], name=op.f('script_steps_script_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('script_steps_pkey'))
    )
    op.drop_index(op.f('ix_ivr_routes_node_id'), table_name='ivr_routes')
    op.drop_table('ivr_routes')
    op.drop_index(op.f('ix_ivr_nodes_script_id'), table_name='ivr_nodes')
    op.drop_table('ivr_nodes')
    # ### end Alembic commands ###
