"""Remove DNC and Timezones

Revision ID: 9d7560b63b4b
Revises: 76f068e4e8a8
Create Date: 2026-04-07 19:39:04.855440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9d7560b63b4b'
down_revision: Union[str, Sequence[str], None] = '76f068e4e8a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'respect_local_tz')
    op.drop_column('campaigns', 'call_window_end')
    op.drop_column('campaigns', 'call_window_start')
    op.drop_column('campaigns', 'timezone')
    op.drop_column('contacts', 'is_dnc')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('is_dnc', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('campaigns', sa.Column('timezone', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('campaigns', sa.Column('call_window_start', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('campaigns', sa.Column('call_window_end', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('campaigns', sa.Column('respect_local_tz', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
