"""audio_file_fks_on_delete_set_null

Revision ID: a2515f1dc80c
Revises: 394ec3fb2798
Create Date: 2026-04-11 22:20:22.322333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2515f1dc80c'
down_revision: Union[str, Sequence[str], None] = '394ec3fb2798'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('campaigns_vm_drop_audio_id_fkey'), 'campaigns', type_='foreignkey')
    op.create_foreign_key(None, 'campaigns', 'audio_files', ['vm_drop_audio_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('ivr_nodes_prompt_audio_id_fkey'), 'ivr_nodes', type_='foreignkey')
    op.create_foreign_key(None, 'ivr_nodes', 'audio_files', ['prompt_audio_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('ivr_routes_response_audio_id_fkey'), 'ivr_routes', type_='foreignkey')
    op.create_foreign_key(None, 'ivr_routes', 'audio_files', ['response_audio_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ivr_routes', type_='foreignkey')
    op.create_foreign_key(op.f('ivr_routes_response_audio_id_fkey'), 'ivr_routes', 'audio_files', ['response_audio_id'], ['id'])
    op.drop_constraint(None, 'ivr_nodes', type_='foreignkey')
    op.create_foreign_key(op.f('ivr_nodes_prompt_audio_id_fkey'), 'ivr_nodes', 'audio_files', ['prompt_audio_id'], ['id'])
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.create_foreign_key(op.f('campaigns_vm_drop_audio_id_fkey'), 'campaigns', 'audio_files', ['vm_drop_audio_id'], ['id'])
    # ### end Alembic commands ###
