"""add_dial_queue_table

Revision ID: c46b9fd6ddc7
Revises: ce97ec604580
Create Date: 2026-04-07 03:57:10.051117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c46b9fd6ddc7'
down_revision: Union[str, Sequence[str], None] = 'ce97ec604580'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dial_queue',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.String(length=100), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dial_queue_campaign_id'), 'dial_queue', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_dial_queue_locked_by'), 'dial_queue', ['locked_by'], unique=False)
    op.create_index(op.f('ix_dial_queue_next_attempt_at'), 'dial_queue', ['next_attempt_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dial_queue_next_attempt_at'), table_name='dial_queue')
    op.drop_index(op.f('ix_dial_queue_locked_by'), table_name='dial_queue')
    op.drop_index(op.f('ix_dial_queue_campaign_id'), table_name='dial_queue')
    op.drop_table('dial_queue')
    # ### end Alembic commands ###
