"""initial schema

Revision ID: ce97ec604580
Revises: 
Create Date: 2026-04-07 01:48:42.395252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ce97ec604580'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone_or_sip', sa.String(length=500), nullable=False),
    sa.Column('concurrent_cap', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('OFFLINE', 'AVAILABLE', 'ON_CALL', 'WRAP_UP', name='agentstatus'), nullable=True),
    sa.Column('current_calls', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audio_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('original_name', sa.String(length=500), nullable=True),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('caller_ids',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact_lists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('total_contacts', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sip_gateways',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sip_server', sa.String(length=500), nullable=False),
    sa.Column('auth_type', sa.Enum('PASSWORD', 'IP_BASED', name='gatewayauthtype'), nullable=False),
    sa.Column('sip_username', sa.String(length=255), nullable=True),
    sa.Column('sip_password', sa.String(length=255), nullable=True),
    sa.Column('max_concurrent', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('strip_plus', sa.Boolean(), nullable=True),
    sa.Column('add_prefix', sa.String(length=20), nullable=True),
    sa.Column('use_stir_shaken', sa.Boolean(), nullable=True),
    sa.Column('transport', sa.String(length=10), nullable=True),
    sa.Column('settings_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('call_scripts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('script_type', sa.Enum('VOICE_BROADCAST', 'PRESS_ONE', 'AUTO_DIAL', name='campaigntype'), nullable=False),
    sa.Column('transfer_key', sa.String(length=1), nullable=True),
    sa.Column('hangup_key', sa.String(length=1), nullable=True),
    sa.Column('enable_hangup_response', sa.Boolean(), nullable=True),
    sa.Column('enable_wrong_key_response', sa.Boolean(), nullable=True),
    sa.Column('transfer_response_audio_id', sa.UUID(), nullable=True),
    sa.Column('hangup_response_audio_id', sa.UUID(), nullable=True),
    sa.Column('wrong_key_response_audio_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['hangup_response_audio_id'], ['audio_files.id'], ),
    sa.ForeignKeyConstraint(['transfer_response_audio_id'], ['audio_files.id'], ),
    sa.ForeignKeyConstraint(['wrong_key_response_audio_id'], ['audio_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('list_id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(length=30), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('zip_code', sa.String(length=20), nullable=True),
    sa.Column('country_code', sa.String(length=5), nullable=True),
    sa.Column('misc_data_1', sa.Text(), nullable=True),
    sa.Column('misc_data_2', sa.Text(), nullable=True),
    sa.Column('misc_data_3', sa.Text(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_dnc', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['list_id'], ['contact_lists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_list_id'), 'contacts', ['list_id'], unique=False)
    op.create_index(op.f('ix_contacts_phone_number'), 'contacts', ['phone_number'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'PAUSED', 'COMPLETE', 'ABORTED', name='campaignstatus'), nullable=True),
    sa.Column('script_id', sa.UUID(), nullable=False),
    sa.Column('max_concurrent_calls', sa.Integer(), nullable=True),
    sa.Column('calls_per_second', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('ring_timeout_sec', sa.Integer(), nullable=True),
    sa.Column('retry_attempts', sa.Integer(), nullable=True),
    sa.Column('retry_delay_min', sa.Integer(), nullable=True),
    sa.Column('call_window_start', sa.Time(), nullable=True),
    sa.Column('call_window_end', sa.Time(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('respect_local_tz', sa.Boolean(), nullable=True),
    sa.Column('enable_amd', sa.Boolean(), nullable=True),
    sa.Column('hangup_on_voicemail', sa.Boolean(), nullable=True),
    sa.Column('enable_vm_drop', sa.Boolean(), nullable=True),
    sa.Column('use_legacy_dtmf', sa.Boolean(), nullable=True),
    sa.Column('total_contacts', sa.Integer(), nullable=True),
    sa.Column('dialed_count', sa.Integer(), nullable=True),
    sa.Column('answered_count', sa.Integer(), nullable=True),
    sa.Column('transferred_count', sa.Integer(), nullable=True),
    sa.Column('voicemail_count', sa.Integer(), nullable=True),
    sa.Column('failed_count', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['script_id'], ['call_scripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('script_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('script_id', sa.UUID(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('step_type', sa.Enum('AUDIO_FILE', 'TTS', name='scriptsteptype'), nullable=False),
    sa.Column('audio_file_id', sa.UUID(), nullable=True),
    sa.Column('tts_text', sa.Text(), nullable=True),
    sa.Column('tts_voice', sa.String(length=100), nullable=True),
    sa.Column('playlist_type', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['audio_file_id'], ['audio_files.id'], ),
    sa.ForeignKeyConstraint(['script_id'], ['call_scripts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaign_agents',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('campaign_id', 'agent_id')
    )
    op.create_table('campaign_caller_ids',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('caller_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['caller_id'], ['caller_ids.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('campaign_id', 'caller_id')
    )
    op.create_table('campaign_contact_lists',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('list_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['list_id'], ['contact_lists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('campaign_id', 'list_id')
    )
    op.create_table('campaign_sip_gateways',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('gateway_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gateway_id'], ['sip_gateways.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('campaign_id', 'gateway_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('campaign_sip_gateways')
    op.drop_table('campaign_contact_lists')
    op.drop_table('campaign_caller_ids')
    op.drop_table('campaign_agents')
    op.drop_table('script_steps')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_contacts_phone_number'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_list_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_table('call_scripts')
    op.drop_table('sip_gateways')
    op.drop_table('contact_lists')
    op.drop_table('caller_ids')
    op.drop_table('audio_files')
    op.drop_table('agents')
    # ### end Alembic commands ###
